#!/bin/bash
# Generated by Gemini
#!/bin/bash
# Exit immediately if a command exits with a non-zero status.
set -e

# --- 1. Install Prerequisites ---
echo "--- Installing prerequisites (gnupg, nginx, curl)..."
sudo apt-get update
sudo apt-get install -y gnupg nginx curl

# --- 2. Add Aptly GPG Key & Repository ---
echo "--- Setting up the aptly repository..."
KEYRING_FILE="/usr/share/keyrings/aptly-keyring.gpg"
# Download the key, dearmor it, and save it to the keyring file
curl -fsSL https://www.aptly.info/pubkey.txt | sudo gpg --dearmor -o "${KEYRING_FILE}"
# Add the aptly repository, signed by the key we just added
echo "deb [signed-by=${KEYRING_FILE}] https://repo.aptly.info/ stable main" | sudo tee /etc/apt/sources.list.d/aptly.list

# --- 3. Install Aptly ---
echo "--- Installing aptly..."
sudo apt-get update
sudo apt-get install -y aptly

# --- 4. Create and Mirror Ubuntu Repositories ---
echo "--- Creating aptly mirrors for Ubuntu Noble (24.04)..."
aptly mirror create -architectures=amd64 noble-main-universe http://archive.ubuntu.com/ubuntu/ noble main universe
aptly mirror create -architectures=amd64 noble-updates-main-universe http://archive.ubuntu.com/ubuntu/ noble-updates main universe
aptly mirror create -architectures=amd64 noble-security-main-universe http://security.ubuntu.com/ubuntu/ noble-security main universe

echo "--- Updating mirrors (this will download several GB and take a long time)..."
aptly mirror update noble-main-universe
aptly mirror update noble-updates-main-universe
aptly mirror update noble-security-main-universe

# --- 5. Snapshot and Publish the Mirror ---
echo "--- Snapshotting and publishing the repository..."
TIMESTAMP=$(date +%Y%m%d-%H%M)
# Create snapshots
aptly snapshot create noble-main-"${TIMESTAMP}" from mirror noble-main-universe
aptly snapshot create noble-updates-"${TIMESTAMP}" from mirror noble-updates-main-universe
aptly snapshot create noble-security-"${TIMESTAMP}" from mirror noble-security-main-universe
# Merge snapshots into one
aptly snapshot merge -latest noble-complete-"${TIMESTAMP}" noble-main-"${TIMESTAMP}" noble-updates-"${TIMESTAMP}" noble-security-"${TIMESTAMP}"
# Publish the final, merged snapshot
aptly publish snapshot -distribution="noble" noble-complete-"${TIMESTAMP}"

# --- 6. Configure Nginx to Serve the Repository ---
echo "--- Linking repository to the Nginx web root..."
# Remove old link if it exists to prevent errors on re-run
sudo rm -f /var/www/html/aptly
# Create the new link
sudo ln -s "${HOME}/.aptly/public" /var/www/html/aptly

# --- 7. Display Final Instructions ---
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "✅ Aptly mirror setup is complete!"
echo ""
echo "------------------------------------------------------------------"
echo "==> On your OFFLINE client machines, run the following commands:"
echo "------------------------------------------------------------------"
echo ""
echo "# 1. Add the repository's GPG key:"
echo "curl http://${SERVER_IP}/aptly/pubkey.txt | sudo gpg --dearmor -o /usr/share/keyrings/local-ubuntu-mirror.gpg"
echo ""
echo "# 2. Add the repository to your sources list:"
echo "echo \"deb [signed-by=/usr/share/keyrings/local-ubuntu-mirror.gpg] http://${SERVER_IP}/aptly/ noble main\" | sudo tee /etc/apt/sources.list.d/local-mirror.list"
echo ""
echo "# 3. Update apt:"
echo "sudo apt update"
echo ""
